#A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.11.11

before_install:
  - export DJANGO_SETTINGS_MODULE=project.production
  - export PYTHONPATH=$HOME/builds/laze76/mpass-conn-test
  - export PIP_USE_MIRRORS=true

install:
  - pip install -U pip setuptools       
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE conndata;" -U postgres
  - psql -c "CREATE USER conndata with encrypted password 'conndata' createdb;"  -U postgres
  - psql -c "ALTER DATABASE conndata owner to conndata;"  -U postgres   

script:
  - python manage.py test
